services:
  springapp:
    image: ksunil/springboot-app:IMAGE_TAG
    ports:
      - 8080:8080
    networks:
      - custom-overlay
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=sunil
      - MONGO_DB_PASSWORD=sunil@123
    deploy:
      replicas: 2
      update_config:
         parallelism: 1
         #dealy: 30s
      
  mongo:
    image: ksunil/mongodb:1
    networks:
      - custom-overlay
    environment:
     - MONGO_INITDB_ROOT_USERNAME=sunil
     - MONGO_INITDB_ROOT_PASSWORD=sunil@123
    volumes:
      - mongodata:/data/db
networks:
 custom-overlay:
    driver: overlay
volumes:
    mongodata:
      driver: local
