services:
  springapp:
    image: ksunil/springboot-app:latest
    ports:
      - 8080:8080
    networks:
      - custombridge
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=sunil
      - MONGO_DB_PASSWORD=sunil@123
  mongo:
    image: ksunil/mongodb:1
    networks:
      - custombridge
    environment:
     - MONGO_INITDB_ROOT_USERNAME=sunil
     - MONGO_INITDB_ROOT_PASSWORD=sunil@123
networks:
  custombridge:
    driver: bridge
volumes:
    mongodata:
      driver: local
